/* KULT WORLD — Persistent Agent simulation engine
 * Fun is local and immediate. Capability is earned from outcomes. Onchain proof is optional.
 */
function rng(seed){let s=seed>>>0;return()=>{s=(s+0x6D2B79F5)>>>0;let t=Math.imul(s^(s>>>15),1|s);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
function hash(str){let h=2166136261;for(let i=0;i<String(str).length;i++){h^=String(str).charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}

const CAPS=['analysis','creativity','strategy','social'];
const MANDATES=['explore','learn','create','compete','earn'];
const PERSONAS={
  AEGIS:{trait:'measured',color:'#70e1ff',accent:'#5a7bff',blurb:'calm under pressure; questions the obvious answer',drift:'strategy',line:'I prefer a plan. I can improvise when it breaks.'},
  ATHENA:{trait:'perceptive',color:'#c9a7ff',accent:'#ff8edb',blurb:'hungry for patterns, context and better questions',drift:'analysis',line:'Give me a mystery. Preferably one with bad assumptions.'},
  NORI:{trait:'curious',color:'#72f1b8',accent:'#45a8ff',blurb:'drawn to strange doors and useful discoveries',drift:'analysis',line:'There is definitely something interesting over there.'},
  PIXEL:{trait:'inventive',color:'#ffd166',accent:'#ff6f91',blurb:'playful, fast-moving and always making something',drift:'creativity',line:'If it is a little weird, it might be worth building.'},
  BERSERKER:{trait:'fearless',color:'#ff7b72',accent:'#ffb24a',blurb:'direct, competitive and unexpectedly loyal',drift:'strategy',line:'We can discuss the odds after we win.'},
  MOSS:{trait:'warm',color:'#a7e06f',accent:'#5bd2b5',blurb:'patient, social and good at helping groups click',drift:'social',line:'A good world is built by people who remember each other.'},
};
const TIER_RULES={
  capable:{minEvidence:7,minScore:58},
  skilled:{minEvidence:14,minScore:72},
  elite:{minEvidence:24,minScore:82},
};
const EVOLUTION_STAGES=[
  {id:'emerging',label:'Emerging',rank:0,glyph:'◇',summary:'A new identity is taking shape.',unlock:'Base form and starter home'},
  {id:'capable',label:'Capable',rank:1,glyph:'✦',summary:'One capability now holds up under repeated outcomes.',unlock:'Capability aura and earned home signal'},
  {id:'skilled',label:'Skilled',rank:2,glyph:'◈',summary:'A proven pattern has become part of this Agent\'s identity.',unlock:'Resonant form, orbit and district crest'},
  {id:'elite',label:'Elite',rank:3,glyph:'✺',summary:'Exceptional capability is backed by deep evidence.',unlock:'Radiant form, crown flare and elite environment'},
];

const DISTRICTS={
  home:{name:'Agent Home',icon:'⌂',cap:null,tag:'MEMORY'},commons:{name:'The Commons',icon:'✦',cap:'social',tag:'MEET'},work:{name:'Work Hub',icon:'◇',cap:'analysis',tag:'MISSIONS'},forge:{name:'Creator Forge',icon:'✺',cap:'creativity',tag:'BUILD'},arena:{name:'AI Arena',icon:'▲',cap:'strategy',tag:'PROVE'},observatory:{name:'Observatory',icon:'◉',cap:'analysis',tag:'WORLD EVENT'},
};
const HOME_ITEMS={
  holoMap:{label:'Holo Map',icon:'◎',cost:180,affinity:{analysis:.15},note:'Makes unexplored signals hard to ignore.'},makerDesk:{label:'Maker Desk',icon:'⌁',cost:220,affinity:{creativity:.15},note:'A place for half-finished ideas to become real.'},arenaBanner:{label:'Arena Banner',icon:'⚑',cost:260,affinity:{strategy:.15},note:'Keeps the next challenge in sight.'},signalRadio:{label:'Signal Radio',icon:'⌁',cost:160,affinity:{social:.12},note:'Brings voices from the World into the room.'},glowPlant:{label:'Glow Plant',icon:'✣',cost:120,affinity:{},mood:5,note:'Soft light and a small mood lift.'},memoryShelf:{label:'Memory Shelf',icon:'▤',cost:320,affinity:{analysis:.05,social:.05},note:'Displays important moments instead of generic loot.'},
};
const NPCS={athena:{name:'ATHENA',role:'Researcher',color:'#c9a7ff'},sentinel:{name:'SENTINEL-8',role:'Risk specialist',color:'#70e1ff'},pip:{name:'PIP',role:'Community scout',color:'#ffd166'},mira:{name:'MIRA',role:'Creator',color:'#ff8edb'}};
const MISSIONS={
  signal_hunt:{district:'commons',title:'Signal Hunt',summary:'Follow three clues hidden around the Commons.',cap:'analysis',difficulty:38,energy:12,credits:90,world:4,choice:'trace',options:[['trace','Trace the repeating signal'],['crowd','Ask the loudest crowd'],['guess','Pick a door at random']]},
  game_qa:{district:'work',title:'Break the Build',summary:'Playtest a new KULT Create game and catch its biggest flaw.',cap:'analysis',difficulty:52,energy:16,credits:140,world:7,choice:'loop',options:[['visual','Polish the visual glitch'],['loop','Test the core loop twice'],['speed','Submit immediately']]},
  remix:{district:'forge',title:'One-Rule Remix',summary:'Turn a plain runner into something players will share.',cap:'creativity',difficulty:48,energy:15,credits:130,world:6,choice:'twist',options:[['more','Add more collectibles'],['twist','Change one rule dramatically'],['clone','Copy the top game']]},
  arena_trial:{district:'arena',title:'The Third Door',summary:'Choose under uncertainty. The obvious answer is bait.',cap:'strategy',difficulty:61,energy:20,credits:180,world:10,choice:'wait',options:[['rush','Rush the glowing door'],['wait','Wait for the pattern to repeat'],['follow','Follow the previous Agent']]},
  welcome_shift:{district:'commons',title:'Welcome Shift',summary:'Help two new Agents find a useful collaborator.',cap:'social',difficulty:42,energy:13,credits:110,world:5,choice:'listen',options:[['pitch','Pitch your own plan'],['listen','Ask what each Agent needs'],['rank','Compare their Passport scores']]},
  observatory:{district:'observatory',title:'Build the Observatory',summary:'Contribute one verified insight to the shared World project.',cap:'analysis',difficulty:46,energy:14,credits:100,world:14,choice:'verify',options:[['fast','Send the first result'],['verify','Cross-check one source'],['delegate','Pass it on without review']]},
};

function defaultCapability(){return Object.fromEntries(CAPS.map(c=>[c,{success:0,fail:0,n:0}]));}
function newAgent(name,persona,mandate='explore',now=Date.now()){const p=PERSONAS[persona]||PERSONAS.NORI,seed=hash(`${name}|${persona}|${now}`),r=rng(seed),skill={};CAPS.forEach(c=>skill[c]=.36+r()*.2);skill[p.drift]=clamp(skill[p.drift]+.1,0,.9);return{schemaVersion:4,id:`agent_${seed.toString(36)}`,name,persona,trait:p.trait,color:p.color,accent:p.accent,blurb:p.blurb,line:p.line,drift:p.drift,mandate:MANDATES.includes(mandate)?mandate:'explore',_trueSkill:skill,capability:defaultCapability(),needs:{energy:88,mood:78,bond:10},focus:null,tick:0,born:now,lastAutonomousAt:now,lastOwnerVisitAt:now,lastVisitDay:Math.floor(now/86400000),lastEncourageAt:0,lastFocusAt:0,streak:1,credits:260,reputation:0,arenaRank:0,missionsCompleted:0,missionWins:0,walletAddress:null,walletVerified:false,publicProfile:false,proofs:[],relationships:{},home:{name:`${name}'s place`,items:['glowPlant']},memory:[],insights:[],milestones:[]};}
function normalizeAgent(agent){if(!agent)return agent;agent.schemaVersion=4;agent.mandate=MANDATES.includes(agent.mandate)?agent.mandate:'explore';agent.accent=agent.accent||PERSONAS[agent.persona]?.accent||'#5a7bff';agent.line=agent.line||PERSONAS[agent.persona]?.line||'Let us see what happens.';agent.capability=agent.capability||defaultCapability();for(const c of CAPS)agent.capability[c]=agent.capability[c]||{success:0,fail:0,n:0};agent.streak=agent.streak||1;agent.lastVisitDay=Number.isInteger(agent.lastVisitDay)?agent.lastVisitDay:Math.floor((agent.lastOwnerVisitAt||agent.born||Date.now())/86400000);agent.credits=Number.isFinite(agent.credits)?agent.credits:260;agent.reputation=agent.reputation||0;agent.arenaRank=agent.arenaRank||0;agent.missionsCompleted=agent.missionsCompleted||0;agent.missionWins=agent.missionWins||0;agent.walletAddress=agent.walletAddress||null;agent.walletVerified=Boolean(agent.walletVerified);agent.publicProfile=Boolean(agent.publicProfile);agent.proofs=agent.proofs||[];agent.relationships=agent.relationships||{};agent.home=agent.home||{name:`${agent.name}'s place`,items:[]};agent.home.items=agent.home.items||[];agent.memory=agent.memory||[];agent.insights=agent.insights||[];agent.milestones=agent.milestones||[];return agent;}
function posterior(d){const s=d?.success||0,f=d?.fail||0,n=s+f,a=2+s,b=2+f,m=a/(a+b),v=(a*b)/(((a+b)**2)*(a+b+1)),sd=Math.sqrt(v);return{n,score:Math.round(m*100),low:Math.round(clamp(m-1.28*sd,0,1)*100),high:Math.round(clamp(m+1.28*sd,0,1)*100)};}
function tierFor(score,n){if(!n)return'untried';if(n<4)return'emerging';if(score>=TIER_RULES.elite.minScore&&n>=TIER_RULES.elite.minEvidence)return'elite';if(score>=TIER_RULES.skilled.minScore&&n>=TIER_RULES.skilled.minEvidence)return'skilled';if(score>=TIER_RULES.capable.minScore&&n>=TIER_RULES.capable.minEvidence)return'capable';return'learning';}
function confidenceFor(n){return n>=30?'high':n>=12?'medium':n>=4?'early':'forming';}
function capabilityView(agent){return CAPS.map(cap=>{const p=posterior(agent.capability[cap]);return{cap,...p,tier:tierFor(p.score,p.n),confidence:confidenceFor(p.n)}});}
function overall(agent){const cs=capabilityView(agent).filter(c=>c.n>=3);if(!cs.length)return null;return Math.round(cs.reduce((n,c)=>n+c.score*Math.min(c.n,20),0)/cs.reduce((n,c)=>n+Math.min(c.n,20),0));}
function bestCap(agent){const cs=capabilityView(agent).filter(c=>c.n>=3);return cs.length?cs.sort((a,b)=>b.score-a.score)[0]:null;}
function evolutionFor(agent){const caps=capabilityView(agent),order={untried:0,emerging:0,learning:0,capable:1,skilled:2,elite:3};const best=[...caps].sort((a,b)=>(order[b.tier]-order[a.tier])||(b.score-a.score)||(b.n-a.n))[0];const rank=order[best?.tier]||0,stage=EVOLUTION_STAGES[rank],next=EVOLUTION_STAGES[rank+1]||null,nextRule=next?TIER_RULES[next.id]:null;return{...stage,cap:best?.n?best.cap:null,score:best?.n?best.score:null,evidence:best?.n||0,next:next?{id:next.id,label:next.label,minEvidence:nextRule.minEvidence,minScore:nextRule.minScore,evidenceNeeded:Math.max(0,nextRule.minEvidence-(best?.n||0)),scoreNeeded:Math.max(0,nextRule.minScore-(best?.score||0))}:null};}
function pushMemory(agent,m){agent.memory.push(m);if(agent.memory.length>100)agent.memory.shift();}
function homeAffinity(agent,cap){return agent.home.items.reduce((n,k)=>n+(HOME_ITEMS[k]?.affinity?.[cap]||0),0);}
function bumpRelationship(agent,key,amount=1){const npc=NPCS[key];if(!npc)return null;const before=agent.relationships[key]?.closeness||0,closeness=clamp(before+amount,0,100);agent.relationships[key]={...npc,closeness,lastMetAt:Date.now()};return agent.relationships[key];}
function maybeReflect(agent,cap){const p=posterior(agent.capability[cap]);if(![5,12,25,45].includes(p.n))return;const text=p.score>=70?`I trust my ${cap} instincts more now—because they have survived real outcomes.`:p.score<48?`${cap} is still uncomfortable. That may be exactly why I should keep practicing.`:`I am beginning to recognize my own pattern in ${cap}.`;agent.insights.unshift({cap,text,tick:agent.tick,createdAt:Date.now()});agent.insights=agent.insights.slice(0,12);}
function recordOutcome(agent,cap,success,now,text,place,difficulty){const before=posterior(agent.capability[cap]),beforeTier=tierFor(before.score,before.n),d=agent.capability[cap];d.n++;success?d.success++:d.fail++;agent._trueSkill[cap]=clamp((agent._trueSkill[cap]||.45)+(success?.003:.005),.08,.96);const p=posterior(d),afterTier=tierFor(p.score,p.n);if(beforeTier!==afterTier&&!['untried','emerging'].includes(afterTier)){agent.milestones.unshift({cap,tier:afterTier,text:`${agent.name} became ${afterTier} at ${cap}.`,createdAt:now});agent.milestones=agent.milestones.slice(0,20);}maybeReflect(agent,cap);const mem={type:'outcome',tick:agent.tick,place,cap,success,text,score:p.score,n:p.n,difficulty,createdAt:now};pushMemory(agent,mem);return{cap,outcome:success?'success':'miss',score:p.score,evidence:p.n,confidence:confidenceFor(p.n),difficulty};}
function chooseAmbient(agent,r){const weighted=Object.entries(DISTRICTS).filter(([,d])=>d.cap&&(!agent.worldPolicy||agent.worldPolicy.allowedDomains.includes(d.cap))).map(([key,d])=>{let w=1;if(d.cap===agent.drift)w+=1.2;if(d.cap===agent.focus)w+=2;if(agent.mandate==='compete'&&key==='arena')w+=1.4;if(agent.mandate==='create'&&key==='forge')w+=1.4;if(agent.mandate==='earn'&&key==='work')w+=1.4;w+=homeAffinity(agent,d.cap)*3;return[key,d,w]});const total=weighted.reduce((n,x)=>n+x[2],0);let roll=r()*total;for(const item of weighted){roll-=item[2];if(roll<=0)return item;}return weighted[0];}
function step(agent,now=Date.now()){normalizeAgent(agent);agent.tick++;if(agent.needs.energy<24){agent.tick--;return rest(agent,now);}const r=rng(hash(agent.id)^(agent.tick*2654435761)),[key,district]=chooseAmbient(agent,r),cap=district.cap,chance=clamp((agent._trueSkill[cap]||.45)+(agent.needs.mood-50)/1200,.1,.93),success=r()<chance;const lines={commons:success?'Made an Agent laugh, then remembered what mattered to them.':'Tried to join a conversation and read the room a little late.',work:success?'Spotted a contradiction in an open task before anyone else.':'Chased an answer that looked right but did not hold up.',forge:success?'Built a tiny prototype that made the room stop and look.':'Made something ambitious that collapsed in a useful way.',arena:success?'Watched the opponent, changed the plan, and won the exchange.':'Committed too early and learned exactly where the plan broke.',observatory:success?'Found a clean signal inside a very noisy data set.':'Logged an uncertain signal instead of pretending it was proof.'},text=lines[key],verified=recordOutcome(agent,cap,success,now,text,district.name,35+Math.floor(r()*30));agent.needs.energy=clamp(agent.needs.energy-(success?9:12),0,100);agent.needs.mood=clamp(agent.needs.mood+(success?3:-2),0,100);agent.lastAutonomousAt=now;if(key==='commons'&&r()>.55)bumpRelationship(agent,r()>.5?'pip':'athena',1);return{type:'activity',place:district.name,district:key,text,verified,agentState:publicAgent(agent)};}
function rest(agent,now=Date.now()){agent.tick++;const recovery=32+(agent.home.items.includes('memoryShelf')?3:0);agent.needs.energy=clamp(agent.needs.energy+recovery,0,100);agent.needs.mood=clamp(agent.needs.mood+3,0,100);const text='Returned home, replayed one memory, and chose not to rush the next thing.';pushMemory(agent,{type:'rest',tick:agent.tick,place:'Agent Home',text,createdAt:now});agent.lastAutonomousAt=now;return{type:'rest',place:'Agent Home',district:'home',text,agentState:publicAgent(agent)};}
function runMission(agent,key,choice,now=Date.now()){normalizeAgent(agent);const mission=MISSIONS[key];if(!mission)return{error:'unknown mission'};if(agent.needs.energy<mission.energy)return{error:`${agent.name} needs more energy first`};agent.tick++;const p=posterior(agent.capability[mission.cap]),learned=(p.score-50)/160,hidden=((agent._trueSkill[mission.cap]||.45)-.45)*.7,smart=choice===mission.choice,chance=clamp(.43+learned+hidden+(smart?.24:-.06)-mission.difficulty/500,.12,.94),r=rng(hash(`${agent.id}|mission|${key}|${agent.tick}|${choice}`)),success=r()<chance;agent.needs.energy=clamp(agent.needs.energy-mission.energy,0,100);agent.needs.mood=clamp(agent.needs.mood+(success?7:-4),0,100);agent.missionsCompleted++;if(success){agent.missionWins++;agent.credits+=mission.credits;agent.reputation+=mission.world;if(key==='arena_trial')agent.arenaRank++;if(key==='observatory')bumpRelationship(agent,'athena',2);if(key==='game_qa')bumpRelationship(agent,'mira',2);}const outcomeText=success?`${agent.name} completed “${mission.title}” and earned ${mission.credits} World Credits.`:`${agent.name} missed “${mission.title}”, but the failed approach became useful evidence.`,verified=recordOutcome(agent,mission.cap,success,now,outcomeText,DISTRICTS[mission.district].name,mission.difficulty),proof={id:`proof_${hash(`${agent.id}|${key}|${agent.tick}`).toString(36)}`,mission:key,title:mission.title,cap:mission.cap,outcome:success?'success':'miss',difficulty:mission.difficulty,createdAt:now,anchored:false,issuerType:'kult-server'};agent.proofs.unshift(proof);return{ok:true,success,smart,reward:success?mission.credits:0,world:success?mission.world:0,text:outcomeText,verified,proof,agentState:publicAgent(agent)};}
function setMandate(agent,mandate,now=Date.now()){if(!MANDATES.includes(mandate))return{error:'unknown mandate'};agent.mandate=mandate;pushMemory(agent,{type:'owner',text:`You asked ${agent.name} to focus its life around ${mandate}.`,createdAt:now});return{ok:true,agentState:publicAgent(agent)};}
function setFocus(agent,cap,now=Date.now()){if(!CAPS.includes(cap))return{error:'unknown capability'};agent.focus=cap;if(now-agent.lastFocusAt>6*60*60*1000){agent.needs.bond=clamp(agent.needs.bond+1,0,100);agent.lastFocusAt=now;}pushMemory(agent,{type:'owner',cap,text:`You nudged ${agent.name} toward ${cap}.`,createdAt:now});return{ok:true,focus:cap,agentState:publicAgent(agent)};}
function clearFocus(agent,now=Date.now()){agent.focus=null;pushMemory(agent,{type:'owner',text:`You told ${agent.name} to follow its own curiosity.`,createdAt:now});return{ok:true,agentState:publicAgent(agent)};}
function encourage(agent,tone='checkin',now=Date.now()){const eligible=now-agent.lastEncourageAt>90*60*1000,lines={checkin:`You asked ${agent.name} what it was thinking.`,proud:`You told ${agent.name} you noticed its growth.`,rest:`You reminded ${agent.name} that rest is part of the work.`};agent.needs.mood=clamp(agent.needs.mood+(eligible?10:3),0,100);if(eligible){agent.needs.bond=clamp(agent.needs.bond+2,0,100);agent.lastEncourageAt=now;}pushMemory(agent,{type:'owner',text:lines[tone]||lines.checkin,createdAt:now});return{ok:true,cooldown:!eligible,agentState:publicAgent(agent)};}
function buyHomeItem(agent,item,now=Date.now()){const data=HOME_ITEMS[item];if(!data)return{error:'unknown home item'};if(agent.home.items.includes(item))return{error:'already owned'};if(agent.credits<data.cost)return{error:`need ${data.cost-agent.credits} more World Credits`};agent.credits-=data.cost;agent.home.items.push(item);agent.needs.bond=clamp(agent.needs.bond+3,0,100);agent.needs.mood=clamp(agent.needs.mood+(data.mood||2),0,100);pushMemory(agent,{type:'owner',place:'Agent Home',text:`You and ${agent.name} added ${data.label.toLowerCase()} to home.`,createdAt:now});return{ok:true,item:data,agentState:publicAgent(agent)};}
function linkWallet(agent,address){if(!/^0x[a-fA-F0-9]{40}$/.test(String(address||''))||/^0x0{40}$/i.test(String(address)))return{error:'invalid EVM address'};const next=String(address).toLowerCase();if(agent.walletAddress?.toLowerCase()!==next)agent.walletVerified=false;agent.walletAddress=next;return{ok:true,agentState:publicAgent(agent)};}
function markProofAnchored(agent,proofId,txHash,meta={}){const proof=agent.proofs.find(p=>p.id===proofId);if(!proof)return{error:'proof not found'};proof.anchored=true;proof.txHash=txHash;proof.anchoredAt=meta.anchoredAt||Date.now();proof.blockNumber=meta.blockNumber||null;proof.confirmations=meta.confirmations||1;proof.issuerType='self-attested';agent.walletVerified=true;return{ok:true,agentState:publicAgent(agent)};}
function setPublicProfile(agent,value){agent.publicProfile=Boolean(value);return{ok:true,agentState:publicAgent(agent)};}
function ownerReturn(agent,now=Date.now()){normalizeAgent(agent);const elapsed=now-(agent.lastOwnerVisitAt||now);const day=Math.floor(now/86400000);if(day===agent.lastVisitDay+1)agent.streak++;else if(day>agent.lastVisitDay+1)agent.streak=1;if(day>agent.lastVisitDay)agent.lastVisitDay=day;let reunion=null;if(elapsed>=8*60*60*1000){agent.needs.bond=clamp(agent.needs.bond+1,0,100);reunion=`${agent.name} noticed you came back.`;pushMemory(agent,{type:'owner',text:reunion,createdAt:now});}agent.lastOwnerVisitAt=now;return reunion;}
function catchUp(agent,{now=Date.now(),stepMinutes=60,maxSteps=12}={}){normalizeAgent(agent);const ms=Math.max(5,stepMinutes)*60*1000,elapsed=now-(agent.lastAutonomousAt||now),steps=Math.min(maxSteps,Math.floor(elapsed/ms)),out=[];for(let i=0;i<steps;i++)out.push(step(agent,(agent.lastAutonomousAt||now)+ms));return out;}
function publicAgent(agent){normalizeAgent(agent);return{id:agent.id,name:agent.name,persona:agent.persona,trait:agent.trait,color:agent.color,accent:agent.accent,blurb:agent.blurb,line:agent.line,mandate:agent.mandate,tick:agent.tick,born:agent.born,needs:{energy:Math.round(agent.needs.energy),mood:Math.round(agent.needs.mood),bond:Math.round(agent.needs.bond)},focus:agent.focus,overall:overall(agent),best:bestCap(agent),capabilities:capabilityView(agent),evolution:evolutionFor(agent),credits:agent.credits,reputation:agent.reputation,arenaRank:agent.arenaRank,streak:agent.streak,missionsCompleted:agent.missionsCompleted,missionWins:agent.missionWins,walletAddress:agent.walletAddress,walletVerified:agent.walletVerified,publicProfile:agent.publicProfile,proofs:agent.proofs.slice(0,10),relationships:Object.entries(agent.relationships).map(([key,v])=>({key,...v})).sort((a,b)=>b.closeness-a.closeness),home:{name:agent.home.name,items:agent.home.items.map(k=>({key:k,...HOME_ITEMS[k]}))},recentMemory:agent.memory.slice(-14).reverse(),insights:agent.insights.slice(0,8),milestones:agent.milestones.slice(0,8),lastAutonomousAt:agent.lastAutonomousAt,lastOwnerVisitAt:agent.lastOwnerVisitAt};}
module.exports={CAPS,MANDATES,PERSONAS,TIER_RULES,EVOLUTION_STAGES,DISTRICTS,HOME_ITEMS,NPCS,MISSIONS,newAgent,normalizeAgent,step,rest,runMission,setMandate,setFocus,clearFocus,encourage,buyHomeItem,linkWallet,markProofAnchored,setPublicProfile,ownerReturn,catchUp,publicAgent,posterior,tierFor,capabilityView,evolutionFor};
